default_stages: [pre-push]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
        name: mypy (trace)
        additional_dependencies:
          [types-pkg-resources==0.1.3, types-all, wandb>=0.15.5]
        exclude: >
          (?x)^(
            .*\.pyi$
            |weave/tests/
            |weave/trace_server/tests/
            |weave/legacy/
            |integration_test/
          )
      # TODO: Turn on legacy mypy on split out; not doing for now bc too complicated.
      # - id: mypy
      #   name: mypy (legacy)
      #   additional_dependencies:
      #     [types-pkg-resources==0.1.3, types-all, wandb>=0.15.5]
      #   files: ^weave/legacy
      #   # You have to exclude in 3 places. 1) here. 2) mypi.ini exclude, 3) follow_imports = skip for each module in mypy.ini
      #   exclude: >
      #     (?x)^(
      #       .*\.pyi$
      #       |weave/legacy/tests/
      #       |weave/legacy/weave/ecosystem/
      #       |weave/legacy/weave/panel/
      #       |weave/legacy/weave/ops/
      #     )
      #   args: [--config-file=weave/legacy/mypy.ini]
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: ^examples/.*\.ipynb$
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
