name: Check which tests to run

on:
  workflow_call:
    inputs:
      base_ref:
        description: The base branch to compare against
        type: string
        required: true
    outputs:
      weave_query_tests:
        value: ${{ jobs.check.outputs.weave_query_tests }}
      weave_js_tests:
        value: ${{ jobs.check.outputs.weave_js_tests }}
      trace_server_tests:
        value: ${{ jobs.check.outputs.trace_server_tests }}

env:
  WEAVE_QUERY_PATHS: 'weave_query/'
  WEAVE_JS_PATHS: 'weave-js/'
  TRACE_SERVER_PATHS: 'weave/trace_server/'
  # Everything else is implicitly trace SDK

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      weave_query_tests: ${{ steps.weave_query.outputs.run_tests }}
      weave_js_tests: ${{ steps.weave_js.outputs.run_tests }}
      trace_server_tests: ${{ steps.trace_server.outputs.run_tests }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.head_ref }}
      - name: Get changed files
        id: changed-files
        run: |
          echo "Current ref: ${{ github.ref }}"
            echo "Base ref: ${{ inputs.base_ref }}"
            echo "Event name: ${{ github.event_name }}"
            
            git fetch origin ${{ inputs.base_ref }}
            
            if [ "${{ github.event_name }}" = "pull_request" ]; then
              base_sha=$(git rev-parse origin/${{ inputs.base_ref }})
              head_sha=${{ github.event.pull_request.head.sha }}
            else
              base_sha=$(git rev-parse origin/${{ inputs.base_ref }})
              head_sha=${{ github.sha }}
            fi
            
            echo "Base SHA: $base_sha"
            echo "Head SHA: $head_sha"
            
            changed_files=$(git diff --name-only $base_sha $head_sha)
            
            echo "Changed files:"
            echo "$changed_files"
            
            if [ -z "$changed_files" ]; then
              echo "No files changed"
            else
              echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
              echo "$changed_files" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
            fi
      - name: Echo changed files
        run: |
          echo "Changed files:"
          echo "${{ steps.changed-files.outputs.changed_files }}"
      - id: weave_query
        name: Weave Query Checks
        run: |
          for path in ${{ env.WEAVE_QUERY_PATHS }}; do
            if echo "$changed_files" | grep -q "$path"; then
              echo "run_tests=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "run_tests=false" >> $GITHUB_OUTPUT
      - id: weave_js
        name: Weave JS Checks
        run: |
          for path in ${{ env.WEAVE_JS_PATHS }}; do
            if echo "$changed_files" | grep -q "$path"; then
              echo "run_tests=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "run_tests=false" >> $GITHUB_OUTPUT
      - id: trace_server
        name: Weave Trace Server Checks
        run: |
          for path in ${{ env.CORE_INTEGRATION_PATHS }}; do
            if echo "$changed_files" | grep -q "$path"; then
              echo "run_tests=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "run_tests=false" >> $GITHUB_OUTPUT
      - run: |
          echo "run_tests=${{ steps.weave_query.outputs.run_tests }}"
          echo "run_tests=${{ steps.weave_js.outputs.run_tests }}"
          echo "run_tests=${{ steps.trace_server.outputs.run_tests }}"
