name: Check which tests to run

on:
  workflow_call:
    inputs:
      base_ref:
        description: The base branch to compare against
        type: string
        required: true
    outputs:
      weave_query_tests:
        value: ${{ jobs.check.outputs.weave_query_tests }}
      weave_js_tests:
        value: ${{ jobs.check.outputs.weave_js_tests }}
      trace_server_tests:
        value: ${{ jobs.check.outputs.trace_server_tests }}

env:
  WEAVE_QUERY_PATHS: 'weave_query/'
  WEAVE_JS_PATHS: 'weave-js/'
  TRACE_SERVER_PATHS: 'weave/trace_server/'
  # Everything else is implicitly trace SDK

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      weave_query_tests: ${{ steps.weave_query.outputs.run_tests }}
      weave_js_tests: ${{ steps.weave_js.outputs.run_tests }}
      trace_server_tests: ${{ steps.trace_server.outputs.run_tests }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.head_ref }}
      - name: Get changed files
        id: changed-files
        run: |
          # Get the base branch (the branch we're merging into)
          BASE_BRANCH=${{ inputs.base_ref }}

          # Get the current HEAD commit
          CURRENT_HEAD=$(git rev-parse HEAD)

          # Get the merge base (common ancestor) of the current HEAD and the base branch
          MERGE_BASE=$(git merge-base $BASE_BRANCH $CURRENT_HEAD)

          # Get all changed files between the merge base and the current HEAD
          CHANGED_FILES=$(git diff --name-only $MERGE_BASE $CURRENT_HEAD)

          # Set the output
          echo "all_changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Echo changed files to terminal
        run: |
          echo "Changed files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
      - name: Set changed files output
        run: echo "changed_files=$(echo '${{ steps.changed-files.outputs.all_changed_files }}')" >> $GITHUB_ENV
      - id: weave_query
        name: Weave Query Checks
        run: |
          for path in ${{ env.WEAVE_QUERY_PATHS }}; do
            if echo "$changed_files" | grep -q "$path"; then
              echo "run_tests=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "run_tests=false" >> $GITHUB_OUTPUT
      - id: weave_js
        name: Weave JS Checks
        run: |
          for path in ${{ env.WEAVE_JS_PATHS }}; do
            if echo "$changed_files" | grep -q "$path"; then
              echo "run_tests=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "run_tests=false" >> $GITHUB_OUTPUT
      - id: trace_server
        name: Weave Trace Server Checks
        run: |
          for path in ${{ env.CORE_INTEGRATION_PATHS }}; do
            if echo "$changed_files" | grep -q "$path"; then
              echo "run_tests=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "run_tests=false" >> $GITHUB_OUTPUT
      - run: |
          echo "run_tests=${{ steps.weave_query.outputs.run_tests }}"
          echo "run_tests=${{ steps.weave_js.outputs.run_tests }}"
          echo "run_tests=${{ steps.trace_server.outputs.run_tests }}"
