name: cypress

on:
  push:

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: "pip"
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install package
        run: pip install .
      - name: Install dev dependencies
        run: pip install -r requirements.test.txt
      - name: Start Jupyter notebook server
        run: nohup jupyter notebook --NotebookApp.token=abcd &
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./notebook_test
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: notebook_test/cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: notebook_test/cypress/videos
