name: cypress

on:
  push:

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      # - uses: syphar/restore-pip-download-cache@v1
      #   if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - name: Install package
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: pip install .
      - name: Install test dependencies
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: pip install -r requirements.test.txt
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Run notebooks
        run: pytest -n=auto --nbmake --overwrite examples/vis/Scatter.ipynb
      # - name: Start Jupyter notebook server
      #   run: nohup sh weave_server.sh &
      # - name: Cypress run
      #   uses: cypress-io/github-action@v4
      #   with:
      #     working-directory: ./notebook_test
      #     record: true
      #     browser: chrome
      #   env:
      #     # pass the Dashboard record key as an environment variable
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #     # pass GitHub token to allow accurately detecting a build vs a re-run build
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # # after the test run completes
      # # store videos and any screenshots
      # # NOTE: screenshots will be generated only if E2E test failed
      # # thus we store screenshots only on failures
      # # Alternative: create and commit an empty cypress/screenshots folder
      # # to always have something to upload
      # - uses: actions/upload-artifact@v2
      #   if: failure()
      #   with:
      #     name: cypress-screenshots
      #     path: notebook_test/cypress/screenshots
      # # Test run video was always captured, so this action uses "always()" condition
      # - uses: actions/upload-artifact@v2
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: notebook_test/tcypress/videos
