name: cypress

on:
  push:

jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: "pip"
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install package
        run: pip install .
      - name: Install dev dependencies
        run: pip install -r requirements.test.txt
      - name: Start Jupyter notebook server
        run: nohup jupyter notebook --NotebookApp.token=abcd &
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./notebook_test
