name: cypress

on:
  push:

jobs:
  lint:
    name: Python lint
    runs-on: self-hosted
    container: us-east4-docker.pkg.dev/weave-support-367421/weave-images/weave-test:latest

    steps:
      - uses: actions/checkout@v2

      - run: source /root/venv/bin/activate && pre-commit run --all-files

  test:
    name: Python unit tests
    runs-on: self-hosted
    container: us-east4-docker.pkg.dev/weave-support-367421/weave-images/weave-test:latest
    steps:
      # - uses: datadog/agent-github-action@v1.3
      #   with:
      #     api_key: ${{ secrets.DD_API_KEY }}
      - uses: actions/checkout@v2

      - name: Run tests
        env:
          DD_SERVICE: weave-python
          DD_ENV: ci
        run: source /root/venv/bin/activate && cd weave && pytest --ddtrace

  # nbmake:
  #   name: Run notebooks with nbmake
  #   runs-on: self-hosted
  #   container: us-east4-docker.pkg.dev/weave-support-367421/weave-images/weave-test:latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Run notebooks
  #       run: source /root/venv/bin/activate && export PYTHONPATH=$(pwd) && pytest -n=4 --nbmake --overwrite examples
  #     - name: Upload executed notebooks
  #       uses: actions/upload-artifact@v3
  #       if: always()
  #       with:
  #         name: notebooks
  #         path: examples

  cypress-run:
    name: Notebook and UI tests
    # needs: [lint, test]
    if: always()
    runs-on: self-hosted
    container: us-east4-docker.pkg.dev/weave-support-367421/weave-images/weave-test:latest
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5, 6]
    steps:
      - uses: actions/checkout@v2

      # - name: Download executed notebooks
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: notebooks

      - name: Copy node_modules from container to checkout
        run: cp -R /root/integration_test/node_modules ./integration_test/

      - run: ls
      - run: ls integration_test

      - name: Start weave server
        run: source /root/venv/bin/activate && nohup sh weave_server.sh &
      - name: Wait
        run: sleep 10
      - name: Cypress run
        run: source /root/venv/bin/activate && export PYTHONPATH=$(pwd) && cd integration_test && npx cypress run --record --parallel --browser chrome
        # uses: cypress-io/github-action@v4
        # with:
        #   working-directory: ./integration_test
        #   record: true
        #   parallel: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: integration_test/cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: integration_test/tcypress/videos
