name: notebooks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: "pip"
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install package
        run: pip install -e .
      - name: Install dev dependencies
        run: pip install -r requirements.test.txt
      - name: Install spacy language
        run: python -m spacy download en_core_web_sm
      - name: Run tests
        run: pytest -n=auto --nbmake examples/ tutorial/  --ignore=examples/WB_API.ipynb --ignore=examples/KerasModel.ipynb
